#! /bin/sh

if [ ~/.vimrc ]; then
  echo "This script will delete your shit. Do you want to continue?"
  echo "Say 'yes'"
  read response
  if [ 'yes' = $response ] ; then
    rm ~/.vimrc
  else
    echo "ok"
    exit 
  fi
fi

ln ~/vim/.vimrc ~/.vimrc

# the .vimrc is updated instantly,
# but you'll have to run this every time you update the colors.
cp -R colors ~/.vim/colors/
