#! /bin/sh

if [ -e ~/.vimrc ]; then
  echo "This script will delete your shit. Do you want to continue?"
  echo "Say 'yes'"
  read response
  if [ 'yes' = $response ] ; then
    rm ~/.vimrc
  else
    echo "OK. Nothing happened."
    exit 
  fi
fi

git pull
ln ~/vim/.vimrc ~/.vimrc

# the .vimrc is updated instantly,
# but you'll have to run this every time you update the colors.

if [ ! -d ~/.vim ]
  then
    mkdir ~/.vim
fi

if [ ! -d ~/.vim/bundle/vundle ]
  then
    git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

if [ ! -d ~/.vim/colors ]
  then
    mkdir ~/.vim/colors
fi

cp -R ./colors/* ~/.vim/colors/

echo "Your .vimrc has been updated"
